### ISSUE TITLE
Missing default directives in the 'Add Site' menu when building nginx-ui from source.

### ISSUE THREAD

**Issue by sanvu88** [0xJacky/nginx-ui#218]
**Describe the bug**

Missing default directives in the 'Add Site' menu when building nginx-ui from source.

**To Reproduce**

npx browserslist@latest --update-db
wget -O- https://github.com/0xJacky/nginx-ui/archive/refs/tags/v2.0.0-beta.5.tar.gz | tar -xz
cd nginx-ui-2.0.0-beta.5/app
yarn install
yarn build
cd ..
go build -o nginx-ui -v main.go

**Screenshots**

![image](https://github.com/0xJacky/nginx-ui/assets/12091815/c13b2847-8e06-4b85-a2a3-871005e9ee9c)

**Info:**
 - Server OS: Debian 12
 - Server Arch: x64
 - Nginx UI Version: Version: 2.0.0-beta.5 (75)
 - Your Browser: Google Chrome
 - Node version: v20.10.0
 - yarn version: 1.22.21
 - GO Version: 1.21.4

**Comment by 0xJacky** [comment]
Fixed in 26788f3

**Comment by 0xJacky** [comment]
By the way, I recommend to use pnpm rather than yarn.

Also, the recommend build command of backend is `go build -tags=jsoniter -ldflags "$LD_FLAGS -X 'github.com/0xJacky/Nginx-UI/server/settings.buildTime=$(date +%s)'" -o nginx-ui -v main.go`

Using jsoniter has little bit improvement on perfermance, and you need to set a build time for nginx ui, this will be use to determine whether the browser cache is outdated.
