### ISSUE TITLE
Nginx cannot run when got "host not found in upstream"

### ISSUE THREAD

**Issue by thongbn** [0xJacky/nginx-ui#457]
**Describe the bug**
When restart ngnix in docker then got few service not automatic started, nginx will not continue run (mean cannot access nginx-gui, port 80 wont exported) until all service run

**Expected behavior**
- Should be run normally, ignore un-started service

**Screenshots**
![image](https://github.com/user-attachments/assets/7d168882-47ea-4851-ad61-1d8b20e09444)

**Info (please complete the following information):**
 - Server OS: docker run in centos stream 9
 - Nginx UI Version: nginx-ui:beta 29

**Comment by 0xJacky** [comment]
I’m sorry for any inconvenience caused. This limitation is due to nginx itself, not nginx-ui. We have configured a reverse proxy in nginx to forward requests to nginx-ui. Therefore, to access nginx-ui via port 80, nginx must be running.

However, this does not mean there is no way to access nginx-ui if nginx is not started. You can export the port that nginx-ui is listening on to the host, allowing you to access nginx-ui directly without going through nginx.

**Comment by thongbn** [comment]
> I’m sorry for any inconvenience caused. This limitation is due to nginx itself, not nginx-ui. We have configured a reverse proxy in nginx to forward requests to nginx-ui. Therefore, to access nginx-ui via port 80, nginx must be running.
> 
> However, this does not mean there is no way to access nginx-ui if nginx is not started. You can export the port that nginx-ui is listening on to the host, allowing you to access nginx-ui directly without going through nginx.

Thank for your response, i understood.
